// <auto-generated />
using System;
using Gamma2024.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gamma2024.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240909152204_CreationClasseBDIdentity")]
    partial class CreationClasseBDIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gamma2024.Server.Models.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Appartement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstDomicile")
                        .HasColumnType("bit");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdPersonne")
                        .IsUnique();

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ed0c8308-5012-4008-9adc-dbef0bf1c92c",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOh89MuBaTCojb969WfHoMEnOKXATSB9ajw9wm1ZvOV3WtLc+MRUSxZrlMv5DOFu5g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "1d8ac862-e54d-4f10-b6f8-638808c02967",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c886713-03cb-418e-9e77-070506f15bb2",
                            Email = "client@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT@EXAMPLE.COM",
                            NormalizedUserName = "CLIENT@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJdOZJyc9W2LOY34FHmBQZTAXKmJ7nMaOLh3nZgysq+ya9Yk6GsoQkEv07yzaseBtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "client@example.com"
                        });
                });

            modelBuilder.Entity("Gamma2024.Server.Models.CarteCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeExpiration")
                        .HasColumnType("int");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("MoisExpiration")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("CartesCredit");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotPasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudonyme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comptes");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Encan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebutSoireeCloture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinSoireeCloture")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroEncan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Encans");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.EncanLot", b =>
                {
                    b.Property<int>("NumeroEncan")
                        .HasColumnType("int");

                    b.Property<int>("IdLot")
                        .HasColumnType("int");

                    b.Property<int?>("EncanId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("LotId")
                        .HasColumnType("int");

                    b.HasKey("NumeroEncan", "IdLot");

                    b.HasIndex("EncanId");

                    b.HasIndex("IdLot");

                    b.HasIndex("LotId");

                    b.ToTable("EncanLots");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresseFacturationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstLivree")
                        .HasColumnType("bit");

                    b.Property<int>("IdAdresseFacturation")
                        .HasColumnType("int");

                    b.Property<int>("IdLot")
                        .HasColumnType("int");

                    b.Property<int>("LotId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroFacture")
                        .HasColumnType("int");

                    b.Property<double>("PrixTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AdresseFacturationId");

                    b.HasIndex("LotId");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artiste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientMiseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinVente")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstVendu")
                        .HasColumnType("bit");

                    b.Property<int>("IdCategorie")
                        .HasColumnType("int");

                    b.Property<int?>("IdClientMise")
                        .HasColumnType("int");

                    b.Property<int>("IdVendeur")
                        .HasColumnType("int");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Mise")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEncan")
                        .HasColumnType("int");

                    b.Property<double>("ValeurEstimeMax")
                        .HasColumnType("float");

                    b.Property<double>("ValeurEstimeMin")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClientMiseId");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdVendeur");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdresseId1")
                        .HasColumnType("int");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId1");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdLot")
                        .HasColumnType("int");

                    b.Property<string>("Lien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdLot");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Vendeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPersonne")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPersonne")
                        .IsUnique();

                    b.ToTable("Vendeurs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Administrateur",
                            NormalizedName = "ADMINISTRATEUR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "1d8ac862-e54d-4f10-b6f8-638808c02967",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Administrateur", b =>
                {
                    b.HasBaseType("Gamma2024.Server.Models.ApplicationUser");

                    b.Property<int>("IdCompte")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("int");

                    b.Property<int>("PersonneId")
                        .HasColumnType("int");

                    b.HasIndex("IdCompte")
                        .IsUnique()
                        .HasFilter("[IdCompte] IS NOT NULL");

                    b.HasIndex("IdPersonne")
                        .IsUnique()
                        .HasFilter("[IdPersonne] IS NOT NULL");

                    b.HasIndex("PersonneId");

                    b.HasDiscriminator().HasValue("Administrateur");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Client", b =>
                {
                    b.HasBaseType("Gamma2024.Server.Models.ApplicationUser");

                    b.Property<bool>("EstBloque")
                        .HasColumnType("bit");

                    b.Property<int>("IdCompte")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonne")
                        .HasColumnType("int");

                    b.HasIndex("IdCompte")
                        .IsUnique()
                        .HasFilter("[IdCompte] IS NOT NULL");

                    b.HasIndex("IdPersonne")
                        .IsUnique()
                        .HasFilter("[IdPersonne] IS NOT NULL");

                    b.ToTable("AspNetUsers", t =>
                        {
                            t.Property("IdCompte")
                                .HasColumnName("Client_IdCompte");

                            t.Property("IdPersonne")
                                .HasColumnName("Client_IdPersonne");
                        });

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Adresse", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Personne", null)
                        .WithOne("Adresse")
                        .HasForeignKey("Gamma2024.Server.Models.Adresse", "IdPersonne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gamma2024.Server.Models.CarteCredit", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Client", "Client")
                        .WithMany("CartesCredit")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.EncanLot", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Encan", null)
                        .WithMany("EncanLots")
                        .HasForeignKey("EncanId");

                    b.HasOne("Gamma2024.Server.Models.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("IdLot")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gamma2024.Server.Models.Lot", null)
                        .WithMany("EncanLots")
                        .HasForeignKey("LotId");

                    b.HasOne("Gamma2024.Server.Models.Encan", "Encan")
                        .WithMany()
                        .HasForeignKey("NumeroEncan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Encan");

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Facture", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Adresse", "AdresseFacturation")
                        .WithMany("Factures")
                        .HasForeignKey("AdresseFacturationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamma2024.Server.Models.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdresseFacturation");

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Lot", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Client", "ClientMise")
                        .WithMany()
                        .HasForeignKey("ClientMiseId");

                    b.HasOne("Gamma2024.Server.Models.Categorie", "Categorie")
                        .WithMany("Lots")
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gamma2024.Server.Models.Vendeur", "Vendeur")
                        .WithMany("Lots")
                        .HasForeignKey("IdVendeur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("ClientMise");

                    b.Navigation("Vendeur");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Personne", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Adresse", null)
                        .WithMany("Personnes")
                        .HasForeignKey("AdresseId1");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Photo", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Lot", "Lot")
                        .WithMany("Photos")
                        .HasForeignKey("IdLot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Vendeur", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Personne", "Personne")
                        .WithOne("Vendeur")
                        .HasForeignKey("Gamma2024.Server.Models.Vendeur", "IdPersonne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamma2024.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Administrateur", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Compte", "Compte")
                        .WithOne("Administrateur")
                        .HasForeignKey("Gamma2024.Server.Models.Administrateur", "IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamma2024.Server.Models.Personne", null)
                        .WithOne("Administrateur")
                        .HasForeignKey("Gamma2024.Server.Models.Administrateur", "IdPersonne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamma2024.Server.Models.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Client", b =>
                {
                    b.HasOne("Gamma2024.Server.Models.Compte", "Compte")
                        .WithOne("Client")
                        .HasForeignKey("Gamma2024.Server.Models.Client", "IdCompte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gamma2024.Server.Models.Personne", "Personne")
                        .WithOne("Client")
                        .HasForeignKey("Gamma2024.Server.Models.Client", "IdPersonne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Adresse", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("Personnes");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Categorie", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Compte", b =>
                {
                    b.Navigation("Administrateur")
                        .IsRequired();

                    b.Navigation("Client")
                        .IsRequired();
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Encan", b =>
                {
                    b.Navigation("EncanLots");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Lot", b =>
                {
                    b.Navigation("EncanLots");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Personne", b =>
                {
                    b.Navigation("Administrateur")
                        .IsRequired();

                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("Vendeur")
                        .IsRequired();
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Vendeur", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("Gamma2024.Server.Models.Client", b =>
                {
                    b.Navigation("CartesCredit");
                });
#pragma warning restore 612, 618
        }
    }
}
